language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
sudo: false
env:
  - MIX_ENV=test
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
script:
  - mix mix coveralls.travis
